apiVersion: v1
kind: ConfigMap
metadata:
  name: localdev-nats-config
data:
  nats.conf: |
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222
    
    debug: true
    trace: true
    
    jetstream {
      store_dir: /data/jetstream
      max_mem: 256M
      max_file: 1G
    }

    accounts {
      nats: {
        jetstream: enabled
        users: [
          { user: nats, password: nats }
        ]
      }
    }
    
    authorization {
      default_permissions {
        publish = ">"
        subscribe = ">"
      }
    }
    
    http_port: 8222
    http_base_path: /
