apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdev-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localdev-nats
  template:
    metadata:
      labels:
        app: localdev-nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats
        command:
        - nats-server
        - --config
        - /etc/nats/nats.conf
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      volumes:
      - name: config-volume
        configMap:
          name: localdev-nats-config
