apiVersion: v1
kind: Service
metadata:
  name: localdev-nats
spec:
  selector:
    app: localdev-nats
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: monitor
    port: 8222
    targetPort: monitor
