apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configmap
data:
  Caddyfile: |
    conceptor.lvh.me:80 {
      handle_path /api/* {
        reverse_proxy http://host.docker.internal:44001
      }
      handle_path /api {
        reverse_proxy http://host.docker.internal:44001
      }

      reverse_proxy /* http://host.docker.internal:44002
      reverse_proxy / http://host.docker.internal:44002
    }

